<?php

namespace Proxies\__CG__\Dreamheads\Bundle\LeadCRMBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Form extends \Dreamheads\Bundle\LeadCRMBundle\Entity\Form implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setUser($user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function setRequestCost($requestCost)
    {
        $this->__load();
        return parent::setRequestCost($requestCost);
    }

    public function getRequestCost()
    {
        $this->__load();
        return parent::getRequestCost();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setPostMails($postMails)
    {
        $this->__load();
        return parent::setPostMails($postMails);
    }

    public function getPostMails()
    {
        $this->__load();
        return parent::getPostMails();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPostSms($postSms)
    {
        $this->__load();
        return parent::setPostSms($postSms);
    }

    public function getPostSms()
    {
        $this->__load();
        return parent::getPostSms();
    }

    public function addLead(\Dreamheads\Bundle\LeadCRMBundle\Entity\Lead $leads)
    {
        $this->__load();
        return parent::addLead($leads);
    }

    public function removeLead(\Dreamheads\Bundle\LeadCRMBundle\Entity\Lead $leads)
    {
        $this->__load();
        return parent::removeLead($leads);
    }

    public function getLeads()
    {
        $this->__load();
        return parent::getLeads();
    }

    public function addField(\Dreamheads\Bundle\LeadCRMBundle\Entity\Field $fields)
    {
        $this->__load();
        return parent::addField($fields);
    }

    public function removeField(\Dreamheads\Bundle\LeadCRMBundle\Entity\Field $fields)
    {
        $this->__load();
        return parent::removeField($fields);
    }

    public function getFields()
    {
        $this->__load();
        return parent::getFields();
    }

    public function setSmsName($smsName)
    {
        $this->__load();
        return parent::setSmsName($smsName);
    }

    public function getSmsName()
    {
        $this->__load();
        return parent::getSmsName();
    }

    public function setSuccessText($successText)
    {
        $this->__load();
        return parent::setSuccessText($successText);
    }

    public function getSuccessText()
    {
        $this->__load();
        return parent::getSuccessText();
    }

    public function setFailText($failText)
    {
        $this->__load();
        return parent::setFailText($failText);
    }

    public function getFailText()
    {
        $this->__load();
        return parent::getFailText();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'smsName', 'request_cost', 'email', 'successText', 'failText', 'post_mails', 'phone', 'post_sms', 'user', 'leads', 'fields');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}