<?php

namespace Proxies\__CG__\Dreamheads\Bundle\LeadCRMBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Lead extends \Dreamheads\Bundle\LeadCRMBundle\Entity\Lead implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTime($time)
    {
        $this->__load();
        return parent::setTime($time);
    }

    public function getTime()
    {
        $this->__load();
        return parent::getTime();
    }

    public function setIsBad($isBad)
    {
        $this->__load();
        return parent::setIsBad($isBad);
    }

    public function getIsBad()
    {
        $this->__load();
        return parent::getIsBad();
    }

    public function setComment($comment)
    {
        $this->__load();
        return parent::setComment($comment);
    }

    public function getComment()
    {
        $this->__load();
        return parent::getComment();
    }

    public function setForm($form)
    {
        $this->__load();
        return parent::setForm($form);
    }

    public function getForm()
    {
        $this->__load();
        return parent::getForm();
    }

    public function addCouple(\Dreamheads\Bundle\LeadCRMBundle\Entity\Couple $couples)
    {
        $this->__load();
        return parent::addCouple($couples);
    }

    public function removeCouple(\Dreamheads\Bundle\LeadCRMBundle\Entity\Couple $couples)
    {
        $this->__load();
        return parent::removeCouple($couples);
    }

    public function getCouples()
    {
        $this->__load();
        return parent::getCouples();
    }

    public function setRegion(\Dreamheads\Bundle\LeadCRMBundle\Entity\Region $region = NULL)
    {
        $this->__load();
        return parent::setRegion($region);
    }

    public function getRegion()
    {
        $this->__load();
        return parent::getRegion();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'time', 'is_bad', 'comment', 'form', 'couples', 'region');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}