jms_security_extra:
    secure_all_services: false
    expressions: true

security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        main:
            entity: { class: Dreamheads\Bundle\LeadCRMBundle\Entity\User, property: email }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Dreamheads\Bundle\LeadCRMBundle\Entity\User:
            algorithm: md5
            iterations: 1
            encode_as_base64: false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        external:
            pattern: ^/external
            security: false
        
        login:
            pattern:  ^/login$
            anonymous: ~
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
