<?php

namespace Dreamheads\Bundle\LeadCRMBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class LeadController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Dreamheads\Bundle\LeadCRMBundle\Controller\LeadController();
        return $instance;
    }
}
